# Starter pipeline
- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'SampleConnection1'
    applicationId: '1234'
    stage: 'Build'
    scanPipelineWorkspace: true
    ignoreSystemError: true
    ignoreScanningError: true
    enableDebugLogging: true
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
